name: jobs

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: make setup
      - run: make start
  lint:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - run: make lint
  tests:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - run: make test
